# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift (iOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # >>> CHANGE THIS to your exact scheme name if different
  SCHEME: CrewClock

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.*"

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Detect Xcode container (workspace or project) and list schemes
        id: detect
        shell: bash
        run: |
          set -e
          if ls *.xcworkspace >/dev/null 2>&1; then
            CONTAINER_TYPE="workspace"
            CONTAINER_NAME="$(ls -1 *.xcworkspace | head -n1)"
          elif ls *.xcodeproj >/dev/null 2>&1; then
            CONTAINER_TYPE="project"
            CONTAINER_NAME="$(ls -1 *.xcodeproj | head -n1)"
          else
            echo "No .xcworkspace or .xcodeproj found at repo root"; exit 1
          fi

          echo "CONTAINER_TYPE=$CONTAINER_TYPE" >> $GITHUB_ENV
          echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV

          echo "Detected $CONTAINER_TYPE: $CONTAINER_NAME"
          echo "Available schemes:"
          xcodebuild -list -json -$CONTAINER_TYPE "$CONTAINER_NAME" || true

      - name: Build + Test (Simulator)
        run: |
          set -e
          echo "Using $CONTAINER_TYPE: $CONTAINER_NAME"
          xcodebuild \
            -$CONTAINER_TYPE "$CONTAINER_NAME" \
            -scheme "$SCHEME" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO \
            clean build tests
